# Generated by Django 2.2.10 on 2021-02-09 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0002_auto_20210209_1546'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
