# Generated by Django 2.2.10 on 2021-02-09 16:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('questionnaire', '0008_auto_20210209_1756'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompletedQuiz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('q1', models.CharField(max_length=255, verbose_name='Вопрос1')),
                ('q2', models.CharField(max_length=255, verbose_name='Вопрос2')),
                ('q3', models.CharField(max_length=255, verbose_name='Вопрос3')),
                ('q1ans', models.CharField(max_length=255, verbose_name='Ответ на вопрос1')),
                ('q2ans', models.CharField(max_length=255, verbose_name='Ответ на вопрос2')),
                ('q3ans', models.CharField(max_length=255, verbose_name='Ответ на вопрос3')),
                ('quiz_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quiz', to='questionnaire.Quiz', verbose_name='Опрос')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_user', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь, прошедший опрос')),
            ],
        ),
    ]
