# Generated by Django 2.2.10 on 2021-02-09 16:27

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('questionnaire', '0010_auto_20210209_1909'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='completedquiz',
            unique_together={('user_id', 'quiz_id')},
        ),
    ]
