# Generated by Django 2.2.10 on 2021-02-09 11:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название')),
                ('date_start', models.DateTimeField(auto_now=True, verbose_name='Время начала')),
                ('date_end', models.DateTimeField(verbose_name='Время окончания')),
                ('description', models.TextField(verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Опрос',
                'verbose_name_plural': 'Опросы',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Текст')),
                ('type', models.CharField(choices=[('Текстовый', 'Текстовый'), ('С 1 вариантом', 'С 1 вариантом'), ('С несколькими вариантами', 'С несколькими вариантами')], max_length=24, verbose_name='Тип вопроса')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questionnaire.Quiz', verbose_name='Опрос')),
            ],
        ),
    ]
