# Generated by Django 2.2.10 on 2021-02-09 13:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0006_quiz_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_quiz', to='questionnaire.Quiz', verbose_name='Опрос'),
        ),
    ]
