# Generated by Django 2.2.10 on 2021-02-09 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0011_auto_20210209_1927'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='completedquiz',
            options={'verbose_name': 'Законченный опрос', 'verbose_name_plural': 'Законченные опросы'},
        ),
    ]
